name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y autoconf automake build-essential

    - name: Make configure executable
      run: chmod +x ./configure

    - name: Configure
      run: ./configure
    
    - name: Build
      run: make
    
    - name: Run Tests
      run: make check
    
    - name: Distribution Check
      run: make distcheck
